Add CRUD functionality to Request Interests
mentorpaired/core pull request #73
Opened 2020-08-13 03:17 UTC by Tbones41

create new views file for interests
update serializers.py to include request interest
add request interest urls to urls.py
remove `related_name` code from models.requestinterest
update .gitignore to reflect migration files

2020-08-13 14:54 UTC, Nkoli requested changes
Your fixes look good overall. Please go through the comments I left

2020-08-13 14:54 UTC, Nkoli commented on app/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
Here, you could change this field name to mentor for clarity

2020-08-13 14:54 UTC, Nkoli commented on app/models.py
> +        return f'Interest from {self.user.display_name}'
if you change the field name, don't forget to change the user to mentor or whatever field name you eventually decide on.

2020-08-13 14:54 UTC, Nkoli commented on app/serializers.py
> +            'user',
new field name should be reflected here too

2020-08-13 14:54 UTC, Nkoli commented on app/urls.py
> +        'interests/',
https://github.com/mentorpaired/core/issues/41#issue-598318640 please use the urlpatterns suggested here instead.

2020-08-13 14:54 UTC, Nkoli commented on app/urls.py
> +        'interests/<int:pk>/',
https://github.com/mentorpaired/core/issues/41#issue-598318640 same suggestion as the above one.

2020-09-15 18:15 UTC, kosyfrances requested changes
@Tbones41 I stopped reviewing because a lot of the changes seem to be things we already have, for example https://github.com/mentorpaired/core/pull/69/files. Please can you clean up the PR and only keep changes that is related to this task?

2020-09-15 18:15 UTC, kosyfrances commented on .gitignore
> +app/migrations/0004_auto_20200813_0152.py
There is already `app/migrations` listed on line 135 so this individually specifying the migration files is not necessary. But ideally migration files should not be gitignored. Any reason why you are ignoring them?

2020-09-15 18:15 UTC, kosyfrances commented on .gitignore
> +migrations
I don't think we need to ignore migrations, and we are also not generating migrations in the root folder. Any idea why this is being ignored?

2020-09-15 18:15 UTC, kosyfrances commented on README.md
> +- It is advisable to install Django in a virtual environment. The README uses [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/install.html#basic-installation) to create this en
Please update this block just like we have here https://github.com/mentorpaired/core/pull/81/files, because it gets confusing for newbies when we say `It is advisable to install Django in a virtual environment`, before setting up virtualenv itself

2020-09-15 18:15 UTC, kosyfrances commented on README.md
> +Special thanks to [Kosy](https://github.com/kosyfrances), [Delores](https://github.com/Del-sama) and [Tunde](https://github.com/toystars) for guiding us through the entire app creation process, revie
Is all of the readme not from https://github.com/mentorpaired/core/pull/77/files ? 
How did it become a new change on this PR? Was there some issues with rebase?

2020-09-15 18:15 UTC, kosyfrances commented on README.md
>  Core is written in Python3 and Django 3.0.3.
I see that we currently have `Django 3.0.7.` in the migration files and requirements.txt, so this should be updated on the readme as well

2020-09-15 18:15 UTC, kosyfrances commented on app/oauth.py
> +from oauth2_provider.models import AccessToken
Please rearrange imports following the [PEP 8 guideline ](https://www.python.org/dev/peps/pep-0008/#imports)

```
Imports should be grouped in the following order:

Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports.
```

2020-09-16 10:20 UTC, Del-sama commented on app/models.py
> +        default="https://avatars.githubusercontent.com/u/<userid>", null=True, blank=True)
Are we sure this default will work? Where's `userid` coming from?

2020-09-16 10:29 UTC, Del-sama commented on app/models.py
> +        default="https://avatars.githubusercontent.com/u/<userid>", null=True, blank=True)
Are we sure default will work? Where `userid` coming from?

2020-09-16 10:32 UTC, Del-sama commented
As Kosy said, please rebase against staging so we know what your changes are.

2020-10-07 18:59 UTC, kosyfrances commented
@Tbones41 I will be closing this PR as it is being cleaned up here https://github.com/mentorpaired/core/pull/91

2020-10-07 18:59 UTC, closed without merging